'use strict';
import './modules/app.module';
import './config';
import './services/process.service';
import './services/async.service';
import './services/store.service';
import './directives/changeListRow.directive';
import './directives/smallChart.directive';
import './controllers/main.controller';
